import React from 'react';

const styles = { 
  input: { width: '100%', padding: '10px', margin: '5px 0', border: '1px solid #cbd5e1', borderRadius: '6px', outline: 'none', boxSizing: 'border-box' }, 
  btnPrimary: { padding: '10px 15px', background: '#1E3A8A', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold', width: '100%' }, 
  btnSuccess: { padding: '8px 12px', background: '#059669', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer' }, 
  btnDanger: { padding: '8px 12px', background: '#EF4444', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer' }, 
  btnWarning: { padding: '8px 12px', background: '#FBBF24', color: '#1E3A8A', border: 'none', borderRadius: '6px', cursor: 'pointer' }, 
  card: { background: 'white', padding: '20px', borderRadius: '12px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)', marginBottom: '20px' }, 
  label: { fontSize: '14px', fontWeight: 'bold', color: '#333', marginBottom: '5px', display: 'block', marginTop: '10px' } 
};

export default function ERPViewsAdmin(props) {
  const { page, data, tr, today, expForm, setExpForm, editExpId, setEditExpId, handleAddExpItem, handleRemoveExpItem, handleExpItemChange, handleAddExpense, handleEditExpense, handleDeleteExpense, handlePreviewExpense, handleAddEditVend, vendorForm, setVendorForm, editVendId, handleEditVend, handleAddEditPkg, pkgForm, setPkgForm, editPkgId, handleEditPkg, handleAddEditBrn, brnForm, setBrnForm, editBrnId, handleEditBrn, handleAddEditEmp, empForm, setEmpForm, editEmpId, handleEditEmp, handleAddEditSrv, srvForm, setSrvForm, editSrvId, handleEditSrv, handlePaySalary, handleAddPortal, portalForm, setPortalForm, handleRecharge, handleAddInvestment, investForm, setInvestForm, handleTransfer, transferForm, setTransferForm, handleDelete, exportToExcel } = props;

  const expSubTotal = expForm?.items?.reduce((sum, item) => sum + ((parseFloat(item.qty) || 0) * (parseFloat(item.price) || 0)), 0) || 0;
  const expVat = expSubTotal * ((parseFloat(expForm?.taxRate) || 0) / 100);
  const expGrandTotal = expSubTotal + expVat;

  if (page === 'vendors') return (<div><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}><h2>{tr.vendors}</h2><button onClick={() => exportToExcel(data.vendors, 'Vendors')} style={styles.btnSuccess}>{tr.download_excel}</button></div><div style={styles.card}><form onSubmit={handleAddEditVend} style={{ display: 'flex', gap: '10px' }}><input value={vendorForm.name} onChange={e => setVendorForm({...vendorForm, name: e.target.value})} placeholder="Name" style={styles.input} required /><input value={vendorForm.phone} onChange={e => setVendorForm({...vendorForm, phone: e.target.value})} placeholder="Phone" style={styles.input} /><input type="number" value={vendorForm.balance} onChange={e => setVendorForm({...vendorForm, balance: e.target.value})} placeholder="Balance" style={styles.input} /><button type="submit" style={styles.btnPrimary}>{editVendId ? 'Update' : 'Add'}</button></form></div><table style={{ width: '100%', borderCollapse: 'collapse', background: 'white' }}><thead><tr style={{ background: '#1E3A8A', color: 'white' }}><th style={{ padding: '12px', textAlign: 'left' }}>Name</th><th style={{ padding: '12px' }}>Phone</th><th style={{ padding: '12px' }}>Balance</th><th style={{ padding: '12px' }}>Actions</th></tr></thead><tbody>{data.vendors.map(c => <tr key={c.id} style={{ borderBottom: '1px solid #E2E8F0' }}><td style={{ padding: '12px' }}>{c.name}</td><td style={{ padding: '12px' }}>{c.phone}</td><td style={{ padding: '12px' }}>{c.balance}</td><td style={{ padding: '12px' }}><button onClick={() => handleEditVend(c)} style={styles.btnWarning}>Edit</button><button onClick={() => handleDelete('vendors', c.id)} style={{...styles.btnDanger, marginLeft: '5px'}}>Delete</button></td></tr>)}</tbody></table></div>);

  if (page === 'packages') return (<div><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}><h2>{tr.packages}</h2><button onClick={() => exportToExcel(data.packages, 'Packages')} style={styles.btnSuccess}>{tr.download_excel}</button></div><div style={styles.card}><form onSubmit={handleAddEditPkg} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}><input value={pkgForm.name} onChange={e => setPkgForm({...pkgForm, name: e.target.value})} placeholder="Package Name" style={styles.input} required /><input type="number" value={pkgForm.price} onChange={e => setPkgForm({...pkgForm, price: e.target.value})} placeholder="Price" style={styles.input} required /><input value={pkgForm.duration} onChange={e => setPkgForm({...pkgForm, duration: e.target.value})) placeholder="Duration" style={styles.input} /><input value={pkgForm.inclusions} onChange={e => setPkgForm({...pkgForm, inclusions: e.target.value})} placeholder="Inclusions" style={styles.input} /><input value={pkgForm.desc} onChange={e => setPkgForm({...pkgForm, desc: e.target.value})} placeholder="Description" style={{...styles.input, gridColumn: '1 / -1'}} /><button type="submit" style={{...styles.btnPrimary, gridColumn: '1 / -1'}}>{editPkgId ? 'Update' : 'Add'}</button></form></div><table style={{ width: '100%', borderCollapse: 'collapse', background: 'white' }}><thead><tr style={{ background: '#1E3A8A', color: 'white' }}><th style={{ padding: '12px', textAlign: 'left' }}>Name</th><th style={{ padding: '12px' }}>Duration</th><th style={{ padding: '12px' }}>Price</th><th style={{ padding: '12px' }}>Actions</th></tr></thead><tbody>{data.packages.map(c => <tr key={c.id} style={{ borderBottom: '1px solid #E2E8F0' }}><td style={{ padding: '12px' }}>{c.name}</td><td style={{ padding: '12px' }}>{c.duration}</td><td style={{ padding: '12px' }}>{c.price}</td><td style={{ padding: '12px' }}><button onClick={() => handleEditPkg(c)} style={styles.btnWarning}>Edit</button><button onClick={() => handleDelete('packages', c.id)} style={{...styles.btnDanger, marginLeft: '5px'}}>Delete</button></td></tr>)}</tbody></table></div>);

  if (page === 'branches') return (<div><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}><h2>{tr.branches}</h2><button onClick={() => exportToExcel(data.branches, 'Branches')} style={styles.btnSuccess}>{tr.download_excel}</button></div><div style={styles.card}><form onSubmit={handleAddEditBrn} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '10px' }}><input value={brnForm.name} onChange={e => setBrnForm({...brnForm, name: e.target.value})} placeholder="Branch Name" style={styles.input} required /><input value={brnForm.location} onChange={e => setBrnForm({...brnForm, location: e.target.value})} placeholder="Location" style={styles.input} /><input value={brnForm.phone} onChange={e => setBrnForm({...brnForm, phone: e.target.value})} placeholder="Phone" style={styles.input} /><input value={brnForm.manager} onChange={e => setBrnForm({...brnForm, manager: e.target.value})} placeholder="Manager" style={styles.input} /><input value={brnForm.email} onChange={e => setBrnForm({...brnForm, email: e.target.value})} placeholder="Email" style={styles.input} /><input value={brnForm.timing} onChange={e => setBrnForm({...brnForm, timing: e.target.value})} placeholder="Timing" style={styles.input} /><select value={brnForm.status} onChange={e => setBrnForm({...brnForm, status: e.target.value})} style={styles.input}><option>Active</option><option>Inactive</option></select><button type="submit" style={{...styles.btnPrimary, gridColumn: '1 / -1'}}>{editBrnId ? 'Update' : 'Add'}</button></form></div><table style={{ width: '100%', borderCollapse: 'collapse', background: 'white' }}><thead><tr style={{ background: '#1E3A8A', color: 'white' }}><th style={{ padding: '12px', textAlign: 'left' }}>Name</th><th style={{ padding: '12px' }}>Location</th><th style={{ padding: '12px' }}>Manager</th><th style={{ padding: '12px' }}>Status</th><th style={{ padding: '12px' }}>Actions</th></tr></thead><tbody>{data.branches.map(c => <tr key={c.id} style={{ borderBottom: '1px solid #E2E8F0' }}><td style={{ padding: '12px' }}>{c.name}</td><td style={{ padding: '12px' }}>{c.location}</td><td style={{ padding: '12px' }}>{c.manager}</td><td style={{ padding: '12px' }}>{c.status}</td><td style={{ padding: '12px' }}><button onClick={() => handleEditBrn(c)} style={styles.btnWarning}>Edit</button><button onClick={() => handleDelete('branches', c.id)} style={{...styles.btnDanger, marginLeft: '5px'}}>Delete</button></td></tr>)}</tbody></table></div>);

  if (page === 'portals') return (<div><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}><h2>{tr.portals}</h2><button onClick={() => exportToExcel(data.portals.map(p => ({ Name: p.name, Balance: p.current_balance })), 'Portals')} style={styles.btnSuccess}>{tr.download_excel}</button></div><div style={styles.card}><h3>Add New Portal</h3><form onSubmit={handleAddPortal} style={{ display: 'flex', gap: '10px' }}><input value={portalForm.name} onChange={e => setPortalForm({...portalForm, name: e.target.value})} placeholder="Portal Name" style={styles.input} required /><input type="number" value={portalForm.balance} onChange={e => setPortalForm({...portalForm, balance: e.target.value})} placeholder="Initial Balance" style={styles.input} /><button type="submit" style={styles.btnPrimary}>Add</button></form></div><div style={styles.card}><h3>Recharge Portal</h3><form onSubmit={handleRecharge}><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr auto', gap: '10px' }}><select name="portal" style={styles.input} required>{data.portals.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input type="number" step="0.01" name="amt" placeholder="Amount" style={styles.input} required /><input type="date" name="date" defaultValue={today} style={styles.input} required /><input name="desc" placeholder="Desc" style={styles.input} /><select name="mode" style={styles.input}><option>Cash</option><option>Bank Transfer</option></select><button type="submit" style={styles.btnPrimary}>Recharge</button></div></form></div><table style={{ width: '100%', borderCollapse: 'collapse', background: 'white' }}><thead><tr style={{ background: '#1E3A8A', color: 'white' }}><th style={{ padding: '12px', textAlign: 'left' }}>Name</th><th style={{ padding: '12px' }}>Balance</th><th style={{ padding: '12px' }}>Actions</th></tr></thead><tbody>{data.portals.map(p => <tr key={p.id} style={{ borderBottom: '1px solid #E2E8F0' }}><td style={{ padding: '12px' }}>{p.name}</td><td style={{ padding: '12px', fontWeight: 'bold', color: (p.current_balance || 0) < 0 ? '#EF4444' : '#059669' }}>{(p.current_balance || 0).toFixed(2)}</td><td style={{ padding: '12px' }}><button onClick={() => handleDelete('portals', p.id)} style={styles.btnDanger}>Delete</button></td></tr>)}</tbody></table></div>);

  if (page === 'bank') return (<div><h2>{tr.bank}</h2><div style={styles.card}><h3>Fund Transfer</h3><form onSubmit={handleTransfer} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr auto', gap: '10px', alignItems: 'flex-end' }}><div><label style={styles.label}>From</label><select value={transferForm.from} onChange={e => setTransferForm({...transferForm, from: e.target.value})} style={styles.input}><option>Cash</option><option>Bank</option><option>Investor</option></select></div><div><label style={styles.label}>To</label><select value={transferForm.to} onChange={e => setTransferForm({...transferForm, to: e.target.value})} style={styles.input}><option>Bank</option><option>Cash</option><option>Investor</option></select></div><div><label style={styles.label}>Amount</label><input type="number" step="0.01" value={transferForm.amount} onChange={e => setTransferForm({...transferForm, amount: e.target.value})} style={styles.input} required /></div><div><label style={styles.label}>Date</label><input type="date" value={transferForm.date} onChange={e => setTransferForm({...transferForm, date: e.target.value})} style={styles.input} required /></div><button type="submit" style={styles.btnPrimary}>Transfer</button></form></div><button onClick={() => exportToExcel(data.cashbook, 'Cashbook')} style={styles.btnSuccess}>{tr.download_excel}</button><table style={{ width: '100%', borderCollapse: 'collapse', background: 'white', marginTop: '20px' }}><thead><tr style={{ background: '#1E3A8A', color: 'white' }}><th style={{ padding: '12px', textAlign: 'left' }}>Date</th><th style={{ padding: '12px', textAlign: 'left' }}>Type</th><th style={{ padding: '12px', textAlign: 'left' }}>Desc</th><th style={{ padding: '12px', textAlign: 'left' }}>Amount</th><th style={{ padding: '12px', textAlign: 'left' }}>Action</th></tr></thead><tbody>{data.cashbook.slice(0, 20).map(c => <tr key={c.id} style={{ borderBottom: '1px solid #E2E8F0' }}><td style={{ padding: '12px' }}>{c.trans_date}</td><td style={{ padding: '12px' }}>{c.type}</td><td style={{ padding: '12px' }}>{c.description}</td><td style={{ padding: '12px', color: c.type.includes('In') ? '#059669' : '#EF4444', fontWeight: 'bold' }}>{(c.amount || 0).toFixed(2)}</td><td style={{ padding: '12px' }}><button onClick={() => handleDelete('cashbook', c.id)} style={styles.btnDanger}>Delete</button></td></tr>)}</tbody></table></div>);

  if (page === 'invest') return (<div><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}><h2>{tr.invest}</h2><button onClick={() => exportToExcel(data.investments, 'Investments')} style={styles.btnSuccess}>{tr.download_excel}</button></div><div style={styles.card}><form onSubmit={handleAddInvestment} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr auto', gap: '10px', alignItems: 'flex-end' }}><div><label style={styles.label}>Investor Name</label><input value={investForm.name} onChange={e => setInvestForm({...investForm, name: e.target.value})} style={styles.input} required /></div><div><label style={styles.label}>Amount</label><input type="number" step="0.01" value={investForm.amount} onChange={e => setInvestForm({...investForm, amount: e.target.value})} style={styles.input} required /></div><div><label style={styles.label}>Date of Investment</label><input type="date" value={investForm.date} onChange={e => setInvestForm({...investForm, date: e.target.value})} style={styles.input} required /></div><div><label style={styles.label}>Mode</label><select value={investForm.mode} onChange={e => setInvestForm({...investForm, mode: e.target.value})} style={styles.input}><option>Cash</option><option>Bank Transfer</option></select></div><div><label style={styles.label}>Reason</label><select value={investForm.reason} onChange={e => setInvestForm({...investForm, reason: e.target.value})} style={styles.input}><option>Other</option><option>Recharge for Portal</option><option>Office Expense</option><option>Salary</option></select></div>{investForm.reason === 'Other' && <div><label style={styles.label}>Specify Reason</label><input value={investForm.otherReason} onChange={e => setInvestForm({...investForm, otherReason: e.target.value})} style={styles.input} required /></div>}<div><label style={styles.label}>Desc</label><input value={investForm.desc} onChange={e => setInvestForm({...investForm, desc: e.target.value})} style={styles.input} /></div><button type="submit" style={styles.btnPrimary}>Add</button></form></div><table style={{ width: '100%', borderCollapse: 'collapse', background: 'white' }}><thead><tr style={{ background: '#1E3A8A', color: 'white' }}><th style={{ padding: '12px', textAlign: 'left' }}>Name</th><th style={{ padding: '12px' }}>Amount</th><th style={{ padding: '12px' }}>Date</th><th style={{ padding: '12px' }}>Reason</th><th style={{ padding: '12px' }}>Action</th></tr></thead><tbody>{data.investments.map(i => <tr key={i.id} style={{ borderBottom: '1px solid #E2E8F0' }}><td style={{ padding: '12px' }}>{i.investor_name}</td><td style={{ padding: '12px' }}>{(i.amount || 0).toFixed(2)}</td><td style={{ padding: '12px' }}>{i.invest_date}</td><td style={{ padding: '12px' }}>{i.reason || 'N/A'}</td><td style={{ padding: '12px' }}><button onClick={() => handleDelete('investments', i.id)} style={styles.btnDanger}>Delete</button></td></tr>)}</tbody></table></div>);

  if (page === 'hr') return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '20px' }}><h2>{tr.hr}</h2><button onClick={() => exportToExcel(data.payroll.map(p => ({ Employee: p.employees?.name, Amount: p.amount })), 'Payroll')} style={styles.btnSuccess}>{tr.download_excel}</button></div>
      
      <div style={styles.card}><h3>Add Employee</h3><form onSubmit={handleAddEditEmp} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr auto', gap: '10px' }}><input value={empForm.name} onChange={e => setEmpForm({...empForm, name: e.target.value})} placeholder="Name" style={styles.input} required /><input value={empForm.phone} onChange={e => setEmpForm({...empForm, phone: e.target.value})} placeholder="Phone" style={styles.input} /><input type="number" step="0.01" value={empForm.salary} onChange={e => setEmpForm({...empForm, salary: e.target.value})} placeholder="Salary" style={styles.input} /><select value={empForm.role} onChange={e => setEmpForm({...empForm, role: e.target.value})} style={styles.input}><option>Sales</option><option>Accountant</option><option>Manager</option></select><button type="submit" style={styles.btnPrimary}>{editEmpId ? 'Update' : 'Add'}</button></form></div>
      
      <div style={styles.card}><h3>Add Service</h3><form onSubmit={handleAddEditSrv} style={{ display: 'flex', gap: '10px' }}><input value={srvForm.name} onChange={e => setSrvForm({...srvForm, name: e.target.value})} placeholder="Service Name" style={styles.input} required /><button type="submit" style={styles.btnPrimary}>{editSrvId ? 'Update' : 'Add'}</button></form></div>

      <div style={styles.card}><h3>Pay Salary</h3><form onSubmit={handlePaySalary} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr auto', gap: '10px' }}><select name="emp" style={styles.input} required>{data.employees.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select><input type="number" step="0.01" name="amt" placeholder="Amount" style={styles.input} required /><input type="text" name="month" placeholder="Month (e.g. Oct 2023)" style={styles.input} required /><select name="mode" style={styles.input}><option>Cash</option><option>Bank Transfer</option></select><button type="submit" style={styles.btnPrimary}>Pay</button></form></div>

      <div style={styles.card}>
        <h3>{editExpId ? 'Edit Office Expense' : 'Add Office Expense / Purchase Invoice'}</h3>
        <form onSubmit={handleAddExpense} style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr', gap: '15px' }}>
          <div><label style={styles.label}>Vendor Name</label><input value={expForm.vendor_name} onChange={e => setExpForm({...expForm, vendor_name: e.target.value})} style={styles.input} required /></div>
          <div><label style={styles.label}>Vendor VAT</label><input value={expForm.vendor_vat} onChange={e => setExpForm({...expForm, vendor_vat: e.target.value})} style={styles.input} /></div>
          <div><label style={styles.label}>Date</label><input type="date" value={expForm.expense_date} onChange={e => setExpForm({...expForm, expense_date: e.target.value})} style={styles.input} required /></div>
          <div><label style={styles.label}>Type</label><select value={expForm.expense_type} onChange={e => setExpForm({...expForm, expense_type: e.target.value})} style={styles.input}><option>Office Supplies</option><option>Utility</option><option>Rent</option><option>Software</option><option>Other</option></select></div>
          
          <div style={{ gridColumn: '1 / -1' }}>
            <label style={styles.label}>Items</label>
            {expForm.items.map((item, idx) => (
              <div key={idx} style={{ display: 'flex', gap: '10px', marginBottom: '10px' }}>
                <input value={item.name} onChange={e => handleExpItemChange(idx, 'name', e.target.value)} placeholder="Item Name" style={styles.input} required />
                <input type="number" value={item.qty} onChange={e => handleExpItemChange(idx, 'qty', e.target.value)} placeholder="Qty" style={{...styles.input, maxWidth: '80px'}} required />
                <input type="number" step="0.01" value={item.price} onChange={e => handleExpItemChange(idx, 'price', e.target.value)} placeholder="Unit Price" style={styles.input} required />
                <span style={{ padding: '10px', background: '#f3f4f6', borderRadius: '6px', fontWeight: 'bold' }}>Total: {((parseFloat(item.qty)||0)*(parseFloat(item.price)||0)).toFixed(2)}</span>
                {expForm.items.length > 1 && <button type="button" onClick={() => handleRemoveExpItem(idx)} style={styles.btnDanger}>X</button>}
              </div>
            ))}
            <button type="button" onClick={handleAddExpItem} style={{ ...styles.btnWarning, width: 'auto' }}>+ Add Item</button>
          </div>

          <div><label style={styles.label}>Tax Rate</label><select value={expForm.taxRate} onChange={e => setExpForm({...expForm, taxRate: e.target.value})} style={styles.input}><option value="15">With 15% VAT</option><option value="0">Without VAT (0%)</option></select></div>
          <div><label style={styles.label}>Payment Mode (Auto-Deducts from Account)</label><select value={expForm.payment_mode} onChange={e => setExpForm({...expForm, payment_mode: e.target.value})} style={styles.input}><option>Cash</option><option>Bank Transfer</option><option>Investor</option></select></div>
          <div><label style={styles.label}>Description</label><input value={expForm.desc} onChange={e => setExpForm({...expForm, desc: e.target.value})} style={styles.input} /></div>
          
          <div style={{ gridColumn: '1 / -1', background: '#f8fafc', padding: '10px', borderRadius: '8px', textAlign: 'right' }}>
            <p style={{margin:0}}>Subtotal: {expSubTotal.toFixed(2)} | VAT: {expVat.toFixed(2)} | <b>Grand Total: {expGrandTotal.toFixed(2)}</b></p>
          </div>

          <button type="submit" style={{ ...styles.btnPrimary, gridColumn: '1 / -1' }}>{editExpId ? 'Update Expense' : 'Add Expense & Generate Invoice'}</button>
          {editExpId && <button type="button" onClick={() => { setEditExpId(null); setExpForm({ vendor_name: '', vendor_vat: '', expense_date: today, expense_type: 'Office Supplies', payment_mode: 'Cash', items: [{ name: '', qty: 1, price: 0 }], taxRate: '15', desc: '' }); }} style={{ gridColumn: '1 / -1', padding: '10px', background: '#64748b', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer' }}>Cancel Edit</button>}
        </form>
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse', background: 'white', marginTop: '20px' }}>
        <thead><tr style={{ background: '#1E3A8A', color: 'white' }}><th style={{ padding: '12px', textAlign: 'left' }}>Date</th><th style={{ padding: '12px' }}>Inv No</th><th style={{ padding: '12px' }}>Vendor</th><th style={{ padding: '12px' }}>Type</th><th style={{ padding: '12px' }}>Total</th><th style={{ padding: '12px' }}>Mode</th><th style={{ padding: '12px' }}>Actions</th></tr></thead>
        <tbody>{data.expenses.map(e => <tr key={e.id} style={{ borderBottom: '1px solid #E2E8F0' }}><td style={{ padding: '12px' }}>{e.expense_date}</td><td style={{ padding: '12px' }}>{e.invoice_no}</td><td style={{ padding: '12px' }}>{e.vendor_name}</td><td style={{ padding: '12px' }}>{e.expense_type}</td><td style={{ padding: '12px' }}>{(e.amount || 0).toFixed(2)}</td><td style={{ padding: '12px' }}>{e.payment_mode}</td><td style={{ padding: '12px' }}><button onClick={() => handlePreviewExpense(e)} style={{ ...styles.btnPrimary, padding: '5px 8px', width: 'auto', fontSize: '11px' }}>Preview</button><button onClick={() => handleEditExpense(e)} style={{ marginLeft: '5px', ...styles.btnWarning, padding: '5px 8px', fontSize: '11px' }}>Edit</button><button onClick={() => handleDeleteExpense(e)} style={{ marginLeft: '5px', ...styles.btnDanger, padding: '5px 8px', fontSize: '11px' }}>Delete</button></td></tr>)}</tbody>
      </table>
    </div>
  );

  return null;
}
